name: .NET_StoreManagerApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup ASP .NET
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{env.NUGET_VERSION}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -o Releases
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: StoreManagerApp
        publish-profile: ${{secrets.AZURE_STOREMANAGERAPP_PUBLISH_PROFILE}}
        package: Releases

